var Komorebi = window.Komorebi || {};

Komorebi.MENU_DATA = {
  tes: {
    label: 'Tés',
    icon: 'leaf',
    items: [
      {
        id: 'te-gyokuro',
        name: 'Gyokuro Premium',
        price: '$950',
        shortDesc: 'El rocío de jade. Té verde japonés sombreado, de sabor umami profundo.',
        longDesc: 'Cultivado bajo la sombra durante tres semanas antes de su recolección para maximizar su contenido de L-teanina y clorofila. Este té de infusión sedosa regala notas dulces de hierba fresca de montaña y un final aterciopelado que reconforta el espíritu.',
        image: 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Especialidad',
        duration: '3 min',
      },
      {
        id: 'te-matcha-ceremonial',
        name: 'Matcha Ceremonial',
        price: '$1.100',
        shortDesc: 'Té verde molido de calidad superior procedente de Uji, Kioto.',
        longDesc: 'Un elixir verde vibrante preparado tradicionalmente con batidor de bambú (chasen). Destaca por su cuerpo cremoso, sus notas herbáceas intensas, un toque dulce natural y su profunda capacidad antioxidante.',
        image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Tradicional',
        duration: '2 min',
      },
      {
        id: 'te-oolong-melocoton',
        name: 'Oolong de Melocotón',
        price: '$820',
        shortDesc: 'Té azul semifermentado con sutiles aceites orgánicos de melocotón blanco.',
        longDesc: 'Las hojas semifermentadas de Oolong se fusionan de manera perfecta con la frescura frutal del melocotón silvestre. Ofrece un licor de color ámbar suave, aroma sumamente floral y un dulzor equilibrado.',
        image: 'https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Floral',
        duration: '4 min',
      },
    ],
  },
  cafeteria: {
    label: 'Cafetería',
    icon: 'coffee',
    items: [
      {
        id: 'cafe-flat-white',
        name: 'Flat White de Sésamo',
        price: '$780',
        shortDesc: 'Espresso doble con leche emulsionada y pasta de sésamo negro tostado.',
        longDesc: 'Una propuesta vanguardista que combina el café de especialidad de origen etíope con la cremosidad térrea del sésamo negro japonés. El contraste visual y su textura sedosa crean un perfil sofisticado.',
        image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Autor',
        duration: '3 min',
      },
      {
        id: 'cafe-iced-latte-cardamomo',
        name: 'Iced Cardamom Latte',
        price: '$790',
        shortDesc: 'Café extraído en frío mezclado con leche infusionada en vainas de cardamomo.',
        longDesc: 'Para los amantes del café refrescante. Nuestro espresso reposado sobre hielo se funde con leche fría y un toque botánico artesanal de cardamomo natural triturado en frío.',
        image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Popular',
        duration: '3 min',
      },
    ],
  },
  tortas: {
    label: 'Tortas',
    icon: 'cake',
    items: [
      {
        id: 'cake-mousse-matcha',
        name: 'Domo de Matcha & Frambuesa',
        price: '$1.200',
        shortDesc: 'Mousse de matcha ceremonial sobre bizcocho de almendras y corazón de frambuesa.',
        longDesc: 'Un domo perfecto que equilibra el amargor noble del té verde con la acidez refrescante de las frambuesas silvestres sobre una base crocante de biscuit d\'amande.',
        image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13636?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Exclusivo',
        duration: 'Listo',
      },
      {
        id: 'cake-charlotte-lavanda',
        name: 'Charlotte de Lavanda & Limón',
        price: '$1.050',
        shortDesc: 'Tarta delicada perfumada con flores de lavanda orgánica y curd de limón.',
        longDesc: 'Visualmente poética. Crema ligera infusionada en frío con pétalos de lavanda del huerto, intercalada con bizcochuelos de vainilla y un centro cítrico vibrante que limpia el paladar.',
        image: 'https://images.unsplash.com/photo-1519869325930-281384150729?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Recomendado',
        duration: 'Listo',
      },
    ],
  },
  desayunos: {
    label: 'Desayunos',
    icon: 'sunset',
    items: [
      {
        id: 'desayuno-hikari',
        name: 'Desayuno Hikari',
        price: '$1.600',
        shortDesc: 'Tostada brioche con palta triturada, huevo a baja temperatura y brotes orgánicos.',
        longDesc: 'Nuestra interpretación del clásico. Pan brioche de masa madre tostado con manteca batida, palta de estación y un huevo cocinado lentamente para obtener una yema líquida gloriosa.',
        image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Completo',
        duration: '10 min',
      },
      {
        id: 'desayuno-porridge-avena',
        name: 'Miso-Maple Porridge',
        price: '$980',
        shortDesc: 'Avena cremosa cocida en bebida de coco, jarabe de arce, un toque de miso blanco y frutos secos.',
        longDesc: 'Un tazón reconfortante enriquecido con miso blanco para aportar profundidad umami, cubierto con higos frescos, nueces de pecán tostadas y semillas de sésamo caramelizadas.',
        image: 'https://images.unsplash.com/photo-1517686469429-8faf88b9f7cf?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Nutritivo',
        duration: '7 min',
      },
    ],
  },
  brunch: {
    label: 'Brunch',
    icon: 'sandwich',
    items: [
      {
        id: 'brunch-shinto',
        name: 'Brunch Shinto (Para compartir)',
        price: '$3.400',
        shortDesc: 'Selección curada de panes artesanales, hummus botánico, quesos maduros y frutas de estación.',
        longDesc: 'Una tabla diseñada para compartir que honra la abundancia de nuestra huerta. Incluye hummus de remolacha y eneldo, quesos ahumados locales, higos caramelizados, olivas marinadas y dos infusiones a elección.',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Ideal Compartir',
        duration: '12 min',
      },
      {
        id: 'brunch-shokupan-salmon',
        name: 'Shokupan de Salmón Curado',
        price: '$1.850',
        shortDesc: 'Pan de molde japonés esponjoso con salmón curado en casa, eneldo y emulsión de yuzu.',
        longDesc: 'El increíble pan lácteo japonés ligeramente dorado, acompañado de finas lonjas de salmón curado con remolacha y sal de mar, aderezado con crema agria cítrica de yuzu y hojas tiernas de rúcula.',
        image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Gourmet',
        duration: '8 min',
      },
    ],
  },
  frios: {
    label: 'Fríos',
    icon: 'snowflake',
    items: [
      {
        id: 'frio-kombucha-hibisco',
        name: 'Kombucha de Hibisco & Rosas',
        price: '$750',
        shortDesc: 'Bebida fermentada burbujeante aromatizada con pétalos de rosa y flor de hibisco.',
        longDesc: 'Elaborada artesanalmente mediante un cultivo simbiótico en vasijas de barro. El resultado es una bebida probiótica con finas burbujas, un dulzor cítrico y un retrogusto delicadamente floral.',
        image: 'https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Fermentado Natural',
        duration: 'Listo',
      },
      {
        id: 'frio-matcha-tonic',
        name: 'Matcha Espresso Tonic',
        price: '$850',
        shortDesc: 'Agua tónica premium, rodaja de pepino fresco y un shot flotante de Matcha Ceremonial helado.',
        longDesc: 'El contraste definitivo. La efervescencia dulce y amarga de la tónica se encuentra con la mineralidad refrescante del matcha emulsionado en frío. Servido sobre hielo cristalino.',
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop',
        fallbackImage: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop',
        badge: 'Refrescante',
        duration: '3 min',
      },
    ],
  },
};
